cricket/cricket/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cricket/main/urls.py
"""Django main app entry urls"""
from django.urls import path
from .views import TeamListView, TeamDetailView, MatchesListView, MatchUpdateView,\
    PointsListView

app_name = "main"

urlpatterns = [
    path('', TeamListView.as_view(), name="welcome"),
    path('teams/', TeamListView.as_view(), name="teams"),
    path('teams/<int:pk>/details',
         TeamDetailView.as_view(),
         name="team_details"
         ),
    path('matches/', MatchesListView.as_view(), name="matches"),
    path('match/<int:pk>/update', MatchUpdateView.as_view(), name="match_update"),
    path('points', PointsListView.as_view(), name="points")
]

cricket/main/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Team(models.Model):
    name = models.CharField(max_length=64, unique=True)
    logo_url = models.ImageField(upload_to='images/teams/')
    club_state = models.CharField(max_length=32)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('main:team_details', args=[str(self.pk)])


class Player(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=32)
    lastname = models.CharField(max_length=32)
    image_url = models.ImageField(upload_to='images/players/',
                                  default='images/players/default_image.png'
                                  )
    player_jersey_no = models.SmallIntegerField()
    Country = models.CharField(max_length=32)   # Country should be foreign key to a new table.
    matches = models.IntegerField(default=0)
    run = models.IntegerField(default=0)
    highest_score = models.IntegerField(default=0)
    fifties = models.SmallIntegerField(default=0)
    hundreds = models.SmallIntegerField(default=0)

    def __str__(self):
        return "{} - {}".format(self.lastname, self.team.name)
    
    def get_fullname(self):
        return "{} {}".format(self.firstname, self.lastname) 


class Matches(models.Model):
    left_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="team")
    right_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="opposite_team")
    winner_team = models.CharField(max_length=2, default='0')
    
    class Meta:
        verbose_name_plural = "Matches"

    def __str__(self):
        return "{} Vs {}".format(self.left_team.name, self.right_team.name)
    
    @property
    def get_left_team_name(self):
        return "".format(self.left_team.name)
    
    @property
    def get_right_team_name(self):
        return "".format(self.right_team.name)

cricket/main/forms.py
"""main forms module"""
from django import forms
from .models import Team, Matches


class MatchFixture(forms.Form):
    """Match for multiple choice class"""
    teams = forms.ModelMultipleChoiceField(queryset=Team.objects.all(),
                                           required=True,
                                           widget=forms.CheckboxSelectMultiple())


class MatchUpdate(forms.ModelForm):
    """Match update"""
    class Meta:
        """Meta class"""
        model = Matches
        fields = ('winner_team',)

    def __init__(self, *args, **kwargs):
        super(MatchUpdate, self).__init__(*args, **kwargs)
        self.fields['winner_team'] = forms.ChoiceField(choices=[])

cricket/main/views.py
"""Display module """
import copy
import random
from django.views.generic import ListView, DetailView, FormView
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from django.db.models import Q
from cricket.settings import MATCH_CHOICE
from .utils import rb_mixture
from .models import Team, Player, Matches
from .forms import MatchFixture, MatchUpdate

# Create your views here.


class TeamListView(ListView):
    """Team view/display"""
    model = Team
    template_name = "team_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['team_list'] = self.model.objects.all()
        return context


class TeamDetailView(DetailView):
    """Team details view/display"""
    model = Team
    template_name = "team_details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['team_details'] = Player.objects.filter(team__id=self.kwargs.get("pk"))
        return context


class MatchesListView(FormView):
    """Matches view/display"""
    success_url = reverse_lazy('main:matches')
    form_class = MatchFixture
    template_name = "matches.html"

    def form_valid(self, form):
        team_ids = form.data.getlist('teams')
        random.shuffle(team_ids)
        for each in rb_mixture(team_ids, sets=len(team_ids) * 2 - 2):
            for one in each:
                l_team = Team.objects.get(pk=int(one[0]))
                r_team = Team.objects.get(pk=int(one[1]))
                Matches.objects.create(left_team=l_team, right_team=r_team)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['matches_list'] = Matches.objects.all()
        return context


class MatchUpdateView(UpdateView):
    """match update view/display"""
    model = Matches
    form_class = MatchUpdate
    template_name = 'match_edit_form.html'
    success_url = reverse_lazy("main:matches")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['match'] = self.object
        return context

    def get_form(self, form_class=None):
        choice = copy.copy(MATCH_CHOICE)
        form = super(MatchUpdateView, self).get_form(form_class)
        if len(choice) > 3:
            choice = copy.copy(MATCH_CHOICE)
        choice.insert(0, (self.object.left_team.id, self.object.left_team.name))
        choice.insert(1, (self.object.right_team.id, self.object.right_team.name))
        form.fields['winner_team'].choices = choice
        return form

    def form_valid(self, form):
        form.save()
        return UpdateView.form_valid(self, form)


class PointsListView(ListView):
    """Points view/display"""
    model = Team
    template_name = "points_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teams = self.model.objects.all()
        context['points_list'] = []
        for each in teams:
            won = Matches.objects.filter(winner_team=each.id)
            draw = Matches.objects.filter(winner_team=-2).filter(
                Q(left_team_id=each.id) | Q(right_team_id=each.id)
            )
            context['points_list'].append((each, (len(won)*2)+(len(draw)*1)))
        return context

cricket/main/templates/match_edit_form.html
{% extends "base.html" %}

{% block content %}
    <h2>Match Fixture Winner Update</h2>
   
   	<table style="width: 100%">
   		<tr>
   			<th>Team A</th>
   			<th>VS</th>
   			<th>Team B</th>
   		<tr>
   		<tr>
   			<td><img src="{{ match.left_team.logo_url.url }}" width="30" height="30" alt="img">{{ match.left_team }}</td>
   			<td>VS</th>
   			<td><img src="{{ match.right_team.logo_url.url }}" width="30" height="30" alt="img">{{ match.right_team }}</td>
   		<tr>
   	</table>


    <form method="POST">{% csrf_token %}
		{% for each in form %}
		<div class="myradio">
		  	{{ each.label }}{{ each }}
		</div>
		{% endfor %}
		<a href="{% url 'main:matches' %}">
		   <input type="button" class="btn btn-default" value="Cancel" />
		</a>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
{% endblock %}

cricket/main/templates/matches.html
{% extends "base.html" %}
{% load main_extras %}

{% block content %}
    <h2>Matche Fixtures</h2>
    <p>For create the Match Fixtures, please select two are more teams and submit.</p>
    {% include "matches_form.html" %}
    
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    </div>
    
    <table class="table table-bordered table-hovered "cellspacing='0'>
        <tr>
            <th>SNO</th>
            <th>Team A</th>
    		<th> Verus </th>
    		<th>Team B</th>
    		<th>Winner</th>
            <th>Actions</th>
        </tr>
        {% for each in matches_list %}
        <tr>
            <td> {{ forloop.counter }} </td>
			<td>{{ each.left_team }}</td>
			<td> Vs </td>
			<td> {{ each.right_team }}</td>
			<td> {{ each.winner_team|get_teamname }}</td>
            <td>
                <a class="glyphicon glyphicon-pencil" data-toggle="modal" href="{% url 'main:match_update' each.id %}" data-target="#modal" title="edit item" data-tooltip></a>
            </td>
        </tr>
        {% endfor %}
    </table>
  

{% endblock %}

{% block script %}
$(document).ready(function(){
    $(".check").click(function(){
        $("#id_teams input").prop("checked", true);
    });
    $(".uncheck").click(function(){
        $("#id_teams input").prop("checked", false);
    });
});
{% endblock %}

{% block css %}
	table {
		border: 1px solid;
    	width: 100%;
    }
{% endblock %}

cricket/main/templates/matches_form.html
	<form method="POST">{% csrf_token %}
		{% for each in form %}
		<div class="myradio">
		  	{{ each.label }}{{ each }}
		</div>
		{% endfor %}
        <button type="button" class="check btn btn-default">Check</button>
        <button type="button" class="uncheck btn btn-default">Uncheck</button>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>

cricket/main/templates/points_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Teams Points</h2>
    
    <table class="table table-bordered table-hovered "cellspacing='0'>
    	<tr>
    		<th>Team</th>
    		<th>Points</th>
    	</tr>
    	{% for each in points_list %}
    	<tr>
    		<td><img src="{{ each.0.logo_url.url }}" width="30" height="30" alt="img">{{ each.0.name }}</td>
    		<td>{{ each|last }}</td>
    	</tr>
    	{% endfor %}
    </table>
{% endblock %}

cricket/main/templates/team_details.html
{% extends "base.html" %}

{% block content %}
    <h2>Team Details</h2>
    <p> <img src="{{ object.logo_url.url }}" width="30" height="30" alt="img"> {{ object.name }} </p>
    <table class="table table-bordered table-hovered "cellspacing='0' style="margin-left: 30px;">
    	<tr>
    		<th>Player</th>
    		<th>Country</th>
    	</tr>
        {% for each in team_details %}
        <tr>
			<td><a href="{{ each.get_absolute_url }}"><img src="{{ each.image_url.url }}" width="30" height="30" alt="img"></a>{{ each.get_fullname }}</td>
        	<td>{{ each.Country }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

cricket/main/templates/team_list.html
{% extends "base.html" %}

{% block content %}
    <h2>All Teams</h2>
    <table>
        {% for each in team_list %}
		<tr>
			<td><a href="{{ each.get_absolute_url }}"><img src="{{ each.logo_url.url }}" width="30" height="30" alt="img">{{ each.name }}</a></td>
		</tr>		
        {% endfor %}
    </table>
{% endblock %}

cricket/templates/base.html
{% load static %}
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->
        <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
        <style>
        	{% block css %}
    		{% endblock %}
    	</style>
    </head>
    <body>
	    <ul>
		  <li><a href="{% url 'main:welcome' %}">Teams</a></li>
		  <li><a href="{% url 'main:matches' %}">Matches</a></li>
		  <li><a href="{% url 'main:points' %}">Points</a></li>
		</ul>
	    <div class="content container">
	        <div class="row">
	            <div class="col-md-8">
	            {% block content %}
	            {% endblock %}
	            </div>
	        </div>
	    </div>
	</body>
	<script>
	{% block script %}{% endblock %}
	</script>
</html>